version: '3.9'

x-app: &app
  build: .
  env_file: .env

services:
    app:
        <<: *app
        container_name: app
        command: uvicorn --host 0.0.0.0 --port 8000 --proxy-headers --log-level=info app.__main__:app --reload
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - ./.env:/app/.env
        depends_on:
            - redis
    worker:
        <<: *app
        container_name: worker
        command: celery --app app.worker.celery_app worker --loglevel=info
        volumes:
            - .:/app
            - ./.env:/app/.env
        depends_on:
            - app
            - redis

    redis:
        container_name: redis
        image: "redis:7.2.3-alpine"
        env_file: .env
        command: >
            sh -c "redis-server &
            sleep 10 &&
            redis-cli CONFIG SET requirepass $$REDIS_PASSWORD &&
            wait"

    flower:
        <<: *app
        container_name: flower
        command: celery --app app.worker.celery_app flower --port=5555
        ports:
            - 5555:5555
        depends_on:
            - app
            - redis
            - worker
