name: push-registry

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      -
        name: Checkout LFS objects
        run: git lfs checkout
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: #TODO: add registry
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: #TODO: add tag
